### PR TITLE
fix(www): update Icon docs

### LINKED ISSUE #271: Icon Docs plz
The `<Icon />` doc todos from #270 

We cannot generate via `react-docgen`. Also, need some examples/snippets

### PR DESCRIPTION
**Pull request by eckdanny-osi**
closes #271

### CODE REVIEW

**Comment by eckdanny-osi** [comment]
Because `react-docgen` requires all prop meta to be in the same file... but I may be able to clean this up when merging docgens in the macro... I don't really like manual c-&-p for propType doc generation :(

**Comment by eckdanny-osi** [comment]
Ahh. Good news... We can shadow the `fontawesome-react` docgen in a non-exported src artifact (like `foo.docgen`), parse with docgen and recursively merge with _our_ `Icon` docgen. Quick experimentation yields good. just cleaning up another commit. stand by.

File: libs/icons/src/Icon.jsx [hunk 1]
```diff
@@ -3,17 +3,10 @@ import PropTypes from 'prop-types'
...
-  if (typeof set === 'string' && set.length) {
-    if (Array.isArray(iconArg))
-      throw Error(
-        'the `set` prop may only be used with string `icon` | `name` values'
-      )
-    if (typeof iconArg === 'string') return [set, iconArg]
-  }
-  return iconArg
-}
+/**
```
Comment (eckdanny-osi) [inline libs/icons/src/Icon.jsx]: not doing this anymore. remove

Comment (eckdanny-osi) [reply libs/icons/src/Icon.jsx]: removed in 2a32d8d

File: apps/www/src/modules/components/modules/ReactDogenInfo.js [hunk 2]
```diff
@@ -1,13 +1,17 @@
-import docgenComposed from '../../../macros/docgen-composed.macro'
+import docgenComposed from "../../../macros/docgen-composed.macro";
```
Comment (eckdanny-osi) [inline apps/www/src/modules/components/modules/ReactDogenInfo.js]: 😢 autoformat 😢 

ignore for now... fix in #288?

**Comment by eckdanny-osi** [comment]
looking good. merging.
